### ISSUE TITLE
Can you pls keep updating 

### ISSUE THREAD

**Issue by nicebenny23** [joshdon/ProjectSand#3]
This game is the best game many add lava rock as something you can place and something that is affected by physics that’s not a particle

**Comment by nicebenny23** [comment]
You r the best btw

**Comment by joshdon** [comment]
Hey, thanks for the nice comments. I'm busy with some other projects right now, but I'm happy to take pull requests :)

Certain elements (such as lava rock) are intentionally meant to be created, rather than placed directly. That said, it is possible to set the pen color to any element you want with the javascript console.

With respect to physics, the main issue is that most elements are stateless. Only particles carry state. This design choice was to support really fast updates for a large canvas holding lots of elements, all from a single javascript thread.
