### ISSUE TITLE
New Element Idea

### ISSUE THREAD

**Issue by AltruisticNut** [joshdon/ProjectSand#4]
Hi! Been having a lot of fun with this game, it's really been fun to mess around with and figure out JavaScript. I wanted to show/submit a new element I created from the MYSTERY & FIRE interaction over on my own fork. You can test it out over there, if you'd like. You're free to change the name and whatever you'd like to.

I ported it into the vanilla elements.js file for easy conversion below. (Had to change the file extension to .txt though, so you'll need to swap it back. Sorry!).

[elements.txt](https://github.com/joshdon/ProjectSand/files/8065687/elements.txt)

**Comment by joshdon** [comment]
Just checked out your fork, some fun ideas in there.

Which element are you proposing? It looks like mystery + fire still acts as a randomizer.

In the future I recommend opening a pull request to make the proposed diff clearer :)

**Comment by AltruisticNut** [comment]
Thanks for checking put my fork! Sorry I wasn't clear, but I was referring to the Thanos/Dust element combo, which is based on the MYSTERY & FIRE interaction in it's code and functionality, the actual interaction is still the same. Also, I'll be sure to make a pull request next time, I'm still pretty new to Github lol.

**Comment by joshdon** [comment]
Ah, gotcha. I'm traveling at the moment but I'll take a closer look when I get back.

**Comment by joshdon** [comment]
The humans/reproduction/thanos/corrupt interactions are interesting :) I don't think those are quite ready to merge though, but the humans are a fun idea.

The nanites one is actually quite nice. One tweak though that I'd recommend: the speed at which it clones in the upwards direction is nearly instantaneous due to the fact that the canvas is iterated from bottom to top. You can check out how I fixed this type of issue for FUSE.

**Comment by AltruisticNut** [comment]
Happy to see you had fun with some of my elements! 
I'll fix up the Nanites element and send in a pull request once it's ready.

**Comment by joshdon** [comment]
Sounds good!
